-- =====================================================================
-- BANCO DE DADOS DO PORTFÓLIO E DO ADMIN DA ISABELLE BUENO
--
-- ONDE COLAR: no Supabase, menu da esquerda > SQL Editor > New query.
-- Cole este arquivo inteiro e clique em "Run".
--
-- Pode rodar mais de uma vez sem medo: ele não apaga nada que já existe,
-- só cria o que estiver faltando e refaz as regras de segurança.
-- =====================================================================


-- ---------------------------------------------------------------------
-- 1. QUEM É A DONA
-- Esta função responde "sim" só quando quem está logado é a Isabelle.
-- Todas as regras de segurança abaixo usam ela.
-- Se um dia você trocar o e-mail de login, troque aqui também.
-- ---------------------------------------------------------------------
create or replace function public.eh_dona()
returns boolean
language sql
stable
as $$
  select lower(coalesce(auth.jwt() ->> 'email', '')) = 'bellevital@icloud.com';
$$;


-- ---------------------------------------------------------------------
-- 2. TABELA VIDEOS
-- Os vídeos que aparecem no portfólio.
-- visivel = aparece no site ou não (o olhinho do admin).
-- ordem = a posição no site (o arrastar pela alcinha).
-- exemplo = linha de exemplo, que nunca aparece no site.
-- ---------------------------------------------------------------------
create table if not exists public.videos (
  id         bigint generated by default as identity primary key,
  titulo     text not null,
  link       text,
  nicho      text,
  formato    text,
  marca      text,
  destaque   text,
  ordem      integer not null default 0,
  visivel    boolean not null default true,
  exemplo    boolean not null default false,
  criado_em  timestamptz not null default now()
);


-- ---------------------------------------------------------------------
-- 3. TABELA MARCAS
-- A sua base de contatos de empresa.
-- O formulário do site também cai aqui, sempre como "Lead".
-- Os limites de tamanho evitam que alguém mande um texto gigante pelo site.
-- ---------------------------------------------------------------------
create table if not exists public.marcas (
  id              bigint generated by default as identity primary key,
  nome            text not null check (char_length(nome) <= 200),
  instagram       text check (char_length(instagram) <= 200),
  email           text check (char_length(email) <= 200),
  telefone        text check (char_length(telefone) <= 60),
  situacao        text not null default 'Lead'
                  check (situacao in ('Lead', 'Conversando', 'Cliente', 'Parada')),
  obs             text check (char_length(obs) <= 4000),
  ultimo_contato  date,
  exemplo         boolean not null default false,
  criado_em       timestamptz not null default now()
);


-- ---------------------------------------------------------------------
-- 4. TABELA CALENDARIO
-- O que você precisa gravar, editar ou postar, e em que dia.
-- ---------------------------------------------------------------------
create table if not exists public.calendario (
  id         bigint generated by default as identity primary key,
  titulo     text not null,
  marca      text,
  tipo       text not null default 'gravar'
             check (tipo in ('gravar', 'editar', 'postar')),
  data       date not null,
  status     text not null default 'a fazer'
             check (status in ('a fazer', 'feito')),
  exemplo    boolean not null default false,
  criado_em  timestamptz not null default now()
);


-- ---------------------------------------------------------------------
-- 5. TABELA CAMPANHAS
-- Seus trabalhos fechados, com valor, prazo e pagamento.
-- O status segue o funil, nesta ordem:
-- Briefing, Roteiro, Aprovação Roteiro, Gravação, Edição, Aprovado, Entregue.
-- ---------------------------------------------------------------------
create table if not exists public.campanhas (
  id         bigint generated by default as identity primary key,
  campanha   text not null,
  cliente    text,
  tipo       text not null default 'Conteúdo'
             check (tipo in ('Conteúdo', 'Publicidade')),
  status     text not null default 'Briefing'
             check (status in ('Briefing', 'Roteiro', 'Aprovação Roteiro', 'Gravação', 'Edição', 'Aprovado', 'Entregue')),
  qtd        integer not null default 1 check (qtd >= 0),
  valor      numeric(12, 2) not null default 0 check (valor >= 0),
  prazo      date,
  pagamento  text not null default 'pendente'
             check (pagamento in ('pendente', 'pago')),
  ativa      boolean not null default true,
  favorita   boolean not null default false,
  exemplo    boolean not null default false,
  criado_em  timestamptz not null default now()
);


-- ---------------------------------------------------------------------
-- 6. TABELA MARCADOS
-- Guarda o que você já marcou no checklist.
-- Cada item tem uma chave de texto, por exemplo "checklist:capa:0".
-- ---------------------------------------------------------------------
create table if not exists public.marcados (
  chave          text primary key,
  marcado        boolean not null default true,
  atualizado_em  timestamptz not null default now()
);


-- ---------------------------------------------------------------------
-- 7. TABELA VISITAS
-- Cada visita ao portfólio vira uma linha: quando, qual página e de onde veio.
-- Não guarda nada do visitante (nem nome, nem e-mail, nem IP).
-- ---------------------------------------------------------------------
create table if not exists public.visitas (
  id      bigint generated by default as identity primary key,
  data    timestamptz not null default now(),
  pagina  text check (char_length(pagina) <= 300),
  origem  text check (char_length(origem) <= 300)
);

create index if not exists visitas_data_idx on public.visitas (data);


-- ---------------------------------------------------------------------
-- 8. A TRANCA (RLS = Row Level Security)
-- Liga a tranca em TODAS as tabelas. Com a tranca ligada,
-- ninguém faz nada a não ser o que as regras abaixo liberarem.
-- ---------------------------------------------------------------------
alter table public.videos     enable row level security;
alter table public.marcas     enable row level security;
alter table public.calendario enable row level security;
alter table public.campanhas  enable row level security;
alter table public.marcados   enable row level security;
alter table public.visitas    enable row level security;


-- ---------------------------------------------------------------------
-- 9. QUEM PODE MEXER EM QUÊ (permissões básicas)
-- Primeiro tira tudo de quem não está logado (anon) e depois devolve
-- só o mínimo. As regras do bloco 10 ainda filtram linha por linha.
-- ---------------------------------------------------------------------
revoke all on public.videos, public.marcas, public.calendario,
              public.campanhas, public.marcados, public.visitas
  from anon;

grant select, insert, update, delete
  on public.videos, public.marcas, public.calendario,
     public.campanhas, public.marcados, public.visitas
  to authenticated;

grant insert on public.marcas  to anon;   -- formulário do site
grant insert on public.visitas to anon;   -- contador de visitas
grant select on public.videos  to anon;   -- o site mostrar os vídeos visíveis


-- ---------------------------------------------------------------------
-- 10. AS REGRAS DA TRANCA
-- Regra geral: só você, logada, lê e escreve tudo.
-- Exceções, só para quem visita o site:
--   a) pode CRIAR uma marca, e só como "Lead" (formulário do site);
--   b) pode CRIAR uma visita (contador do site);
--   c) pode VER os vídeos marcados como visíveis, porque o portfólio
--      precisa ler essa tabela para mostrar os vídeos. Os vídeos
--      escondidos e a linha de exemplo continuam invisíveis.
-- Ninguém de fora consegue LER marcas, calendário, campanhas,
-- marcados ou visitas.
-- ---------------------------------------------------------------------

-- Apaga as regras antigas (para poder rodar este arquivo de novo)
drop policy if exists "dona faz tudo"                    on public.videos;
drop policy if exists "site ve videos visiveis"          on public.videos;
drop policy if exists "dona faz tudo"                    on public.marcas;
drop policy if exists "site cria lead"                   on public.marcas;
drop policy if exists "dona faz tudo"                    on public.calendario;
drop policy if exists "dona faz tudo"                    on public.campanhas;
drop policy if exists "dona faz tudo"                    on public.marcados;
drop policy if exists "dona faz tudo"                    on public.visitas;
drop policy if exists "site registra visita"             on public.visitas;

-- Você (logada) faz tudo em todas as tabelas
create policy "dona faz tudo" on public.videos
  for all to authenticated using (public.eh_dona()) with check (public.eh_dona());
create policy "dona faz tudo" on public.marcas
  for all to authenticated using (public.eh_dona()) with check (public.eh_dona());
create policy "dona faz tudo" on public.calendario
  for all to authenticated using (public.eh_dona()) with check (public.eh_dona());
create policy "dona faz tudo" on public.campanhas
  for all to authenticated using (public.eh_dona()) with check (public.eh_dona());
create policy "dona faz tudo" on public.marcados
  for all to authenticated using (public.eh_dona()) with check (public.eh_dona());
create policy "dona faz tudo" on public.visitas
  for all to authenticated using (public.eh_dona()) with check (public.eh_dona());

-- Exceção a: o formulário do site cria marcas, sempre como Lead
create policy "site cria lead" on public.marcas
  for insert to anon
  with check (situacao = 'Lead' and exemplo = false);

-- Exceção b: o site registra visitas (com a data de agora, sem inventar data)
create policy "site registra visita" on public.visitas
  for insert to anon
  with check (data > now() - interval '5 minutes' and data < now() + interval '5 minutes');

-- Exceção c: o site lê só os vídeos visíveis que não são exemplo
create policy "site ve videos visiveis" on public.videos
  for select to anon
  using (visivel = true and exemplo = false);


-- ---------------------------------------------------------------------
-- 11. UMA LINHA DE EXEMPLO EM CADA LISTA
-- Só para você ver o formato. Elas aparecem no admin com a etiqueta
-- "exemplo" e podem ser apagadas. Só entram se a tabela estiver vazia.
-- O vídeo de exemplo nasce escondido, então nunca aparece no site.
-- Visitas e checklist começam vazios de verdade (zero).
-- ---------------------------------------------------------------------
insert into public.videos (titulo, link, nicho, formato, marca, destaque, ordem, visivel, exemplo)
select 'Exemplo: título do vídeo', 'https://youtube.com/shorts/', 'beleza', 'Vídeo 9:16',
       'Nome da marca', '0 views', 1, false, true
where not exists (select 1 from public.videos);

insert into public.marcas (nome, instagram, email, telefone, situacao, obs, ultimo_contato, exemplo)
select 'Exemplo: nome da marca', '@perfildamarca', 'contato@marca.com', '(00) 00000-0000',
       'Lead', 'Linha de exemplo. Pode apagar.', current_date, true
where not exists (select 1 from public.marcas);

insert into public.calendario (titulo, marca, tipo, data, status, exemplo)
select 'Exemplo: gravar vídeo de unboxing', 'Nome da marca', 'gravar', current_date + 2, 'a fazer', true
where not exists (select 1 from public.calendario);

insert into public.campanhas (campanha, cliente, tipo, status, qtd, valor, prazo, pagamento, ativa, favorita, exemplo)
select 'Exemplo: campanha de lançamento', 'Nome do cliente', 'Conteúdo', 'Briefing',
       1, 0, current_date + 10, 'pendente', true, false, true
where not exists (select 1 from public.campanhas);


-- ---------------------------------------------------------------------
-- 12. AVISA O SUPABASE QUE TEM TABELA NOVA
-- Faz o painel enxergar as tabelas na hora, sem esperar.
-- ---------------------------------------------------------------------
notify pgrst, 'reload schema';
